spring:
  profiles:
    active: local
  application:
    name: dataservice
  jpa:
    show-sql: true

server:
  port: 8080
---

spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:mem:orange;Mode=PostgreSQL;
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true
      path: /h2-console